In [1]:
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar

In [2]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

In [5]:
print('行列式')
print(linalg.det(matrix))

行列式
-4.0


In [6]:
print('逆行列')
print(linalg.inv(matrix))

逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [7]:
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
